#!/usr/bin/env bash
set -euo pipefail
FILE="app/src/main/java/com/lias/remote/ui/components/HigSheets.kt"
grep -q 'enum class HigSheetPresentation' "$FILE"
grep -q 'HigSheetPresentation.Compact' "$FILE"
grep -q 'HigSheetPresentation.Picker' "$FILE"
grep -q 'HigSheetPresentation.Editor' "$FILE"
grep -q 'HIG_PICKER_VIEWPORT_FRACTION' "$FILE"
grep -q '0.62f' "$FILE"
grep -q 'PresentationDetent.Fraction(' "$FILE"
grep -q 'presentation.detents()' "$FILE"
grep -q 'partialViewportFraction' "$FILE"
grep -q 'fun HigModalSheetPortal(' "$FILE"
grep -q 'completionInFlight' "$FILE"
grep -q 'sheetState.show()' "$FILE"
grep -q 'sheetState.hide()' "$FILE"
grep -q 'navigationBarsPadding()' "$FILE"
grep -q 'imePadding()' "$FILE"
echo "PASS: Plan 3.5 Batch 001 static gate passed."
