// ====================================================================
// File: app/src/main/java/com/lias/remote/repositories/PolicyScheduleMutations.kt
// Version: 14.0.0
//
// Purpose:
//   Race-safe LIAS policy and schedule persistence.
//
// Critical corrections:
//   - No optimistic id="" objects.
//   - Blank ID => POST.
//   - Nonblank ID => PUT.
//   - Canonical server response is committed.
//   - Delete is server-confirmed before local removal.
//   - Failed writes leave last known good UI state untouched.
//   - MutationCoordinator prevents stale refresh overwrite.
// ====================================================================

package com.lias.remote.repositories

import com.lias.remote.core.models.Conflict
import com.lias.remote.core.models.Policy
import com.lias.remote.core.models.Schedule
import com.lias.remote.core.network.ApiResult
import com.lias.remote.core.network.ConflictResponse
import com.lias.remote.core.network.Endpoints
import com.lias.remote.core.network.PolicyValidateRequest

suspend fun EventRepository.validatePolicy(
    scheduleIds: List<String>
): ApiResult<List<Conflict>> {

    val normalized =
        scheduleIds
            .filter {
                it.isNotBlank()
            }
            .distinct()

    val result =
        api.post<
            ConflictResponse,
            PolicyValidateRequest
        >(
            Endpoints.POLICIES_VALIDATE,
            PolicyValidateRequest(
                scheduleIds =
                    normalized
            )
        )

    return when (result) {

        is ApiResult.Success ->
            ApiResult.Success(
                result.data.conflicts
            )

        is ApiResult.ConflictError ->
            ApiResult.Success(
                result.conflicts
            )

        is ApiResult.AuthenticationError ->
            result

        is ApiResult.HttpError ->
            result

        is ApiResult.NetworkError ->
            result

        is ApiResult.SerializationError ->
            result
    }
}

suspend fun EventRepository.savePolicy(
    policy: Policy
): ApiResult<Policy> {

    val key =
        if (
            policy.id.isBlank()
        ) {
            /*
             * New policy IDs are generated by LIAS.
             * Serialize creates as a group so duplicate Save taps cannot
             * create two rules before the first response arrives.
             */
            "policies:create"
        } else {
            "policy:${policy.id}"
        }

    return mutations.mutate(
        resourceKey =
            key
    ) {

        val result =
            if (
                policy.id.isBlank()
            ) {

                api.post<
                    Policy,
                    Policy
                >(
                    Endpoints.POLICIES,
                    policy
                )

            } else {

                api.put<
                    Policy,
                    Policy
                >(
                    Endpoints.policy(
                        policy.id
                    ),
                    policy
                )
            }

        if (
            result is
            ApiResult.Success
        ) {

            val canonical =
                result.data

            upsertPolicy(
                canonical
            )

            /*
             * Policy changes may affect one device, one tag, or every
             * device through global_default. Reconcile after confirmed
             * mutation rather than inventing effective-state changes
             * locally.
             */
            refreshAll()
        }

        result
    }
}

suspend fun EventRepository.deletePolicy(
    policyId: String
): ApiResult<Unit> =
    mutations.mutate(
        resourceKey =
            "policy:$policyId"
    ) {

        if (
            policyId ==
            "global_default"
        ) {
            return@mutate ApiResult.HttpError(
                code =
                    400,
                message =
                    "The Global Access policy cannot be deleted."
            )
        }

        val result =
            api.delete<Unit>(
                Endpoints.policy(
                    policyId
                )
            )

        if (
            result is
            ApiResult.Success
        ) {

            _state.value =
                _state.value.copy(
                    policies =
                        _state.value
                            .policies
                            .filterNot {
                                it.id ==
                                    policyId
                            }
                )

            refreshAll()
        }

        result
    }

suspend fun EventRepository.saveSchedule(
    schedule: Schedule
): ApiResult<Schedule> {

    val key =
        if (
            schedule.id.isBlank()
        ) {
            "schedules:create"
        } else {
            "schedule:${schedule.id}"
        }

    return mutations.mutate(
        resourceKey =
            key
    ) {

        val result =
            if (
                schedule.id.isBlank()
            ) {

                api.post<
                    Schedule,
                    Schedule
                >(
                    Endpoints.SCHEDULES,
                    schedule
                )

            } else {

                api.put<
                    Schedule,
                    Schedule
                >(
                    Endpoints.schedule(
                        schedule.id
                    ),
                    schedule
                )
            }

        if (
            result is
            ApiResult.Success
        ) {

            /*
             * Server may:
             *   - generate the ID
             *   - infer default mode
             *   - normalize persisted representation
             *
             * Use only the returned object.
             */
            upsertSchedule(
                result.data
            )

            refreshAll()
        }

        result
    }
}

suspend fun EventRepository.deleteSchedule(
    scheduleId: String
): ApiResult<Unit> =
    mutations.mutate(
        resourceKey =
            "schedule:$scheduleId"
    ) {

        val result =
            api.delete<Unit>(
                Endpoints.schedule(
                    scheduleId
                )
            )

        if (
            result is
            ApiResult.Success
        ) {

            _state.value =
                _state.value.copy(
                    schedules =
                        _state.value
                            .schedules
                            .filterNot {
                                it.id ==
                                    scheduleId
                            }
                )

            refreshAll()
        }

        result
    }
