// ====================================================================
// File: app/src/main/java/com/lias/remote/core/policy/PolicyDraft.kt
// Version: 17.0.0
//
// Purpose:
//   Mutable-independent editor representation of a LIAS Policy.
//
// Design:
//   - Existing policy IDs are preserved.
//   - New policy ID remains blank and is generated by LIAS.
//   - global_default is never fabricated.
//   - Modern schedule_ids is always used on save.
//   - Legacy schedule_id is normalized away.
// ====================================================================

package com.lias.remote.core.policy

import com.lias.remote.core.models.Policy

data class PolicyDraft(

    val name: String = "",

    val type: String = "tag",

    val targetId: String = "",

    val action: String = "schedule",

    val scheduleIds: Set<String> =
        emptySet(),

    val priorityText: String = "50",

    val enabled: Boolean = true
) {

    companion object {

        fun fromPolicy(
            policy: Policy?
        ): PolicyDraft {

            if (
                policy == null
            ) {
                return PolicyDraft()
            }

            return PolicyDraft(
                name =
                    policy.name,

                type =
                    policy.type,

                targetId =
                    policy.targetID,

                action =
                    policy.action,

                scheduleIds =
                    policy
                        .resolveScheduleIDs()
                        .toSet(),

                priorityText =
                    policy.priority
                        .toString(),

                enabled =
                    if (
                        policy.id ==
                        "global_default"
                    ) {
                        true
                    } else {
                        policy.enabled
                    }
            )
        }
    }

    fun toPolicy(
        initialPolicy: Policy?
    ): Policy {

        val policyId =
            initialPolicy
                ?.id
                .orEmpty()

        val normalizedType =
            type
                .trim()
                .lowercase()

        val normalizedAction =
            action
                .trim()
                .lowercase()

        val normalizedPriority =
            when {

                policyId ==
                    "global_default" ->
                    0

                normalizedType ==
                    "device" ->
                    priorityText
                        .toIntOrNull()
                        ?: 50

                /*
                 * Tag-policy priority is not used by the current LIAS
                 * evaluator. Preserve an existing value for round-trip
                 * compatibility, otherwise use the canonical UI default.
                 */
                else ->
                    initialPolicy
                        ?.priority
                        ?: 50
            }

        return Policy(
            /*
             * Blank means POST /policies and LIAS generates pol_<id>.
             */
            id =
                policyId,

            name =
                name.trim(),

            type =
                normalizedType,

            targetID =
                if (
                    normalizedType ==
                    "global"
                ) {
                    ""
                } else {
                    targetId.trim()
                },

            action =
                normalizedAction,

            scheduleIDs =
                if (
                    normalizedAction ==
                    "schedule"
                ) {
                    scheduleIds
                        .filter {
                            it.isNotBlank()
                        }
                        .distinct()
                } else {
                    emptyList()
                },

            /*
             * Never send both modern and legacy schedule forms.
             */
            scheduleID =
                null,

            priority =
                normalizedPriority,

            enabled =
                if (
                    policyId ==
                    "global_default"
                ) {
                    true
                } else {
                    enabled
                },

            createdAt =
                initialPolicy
                    ?.createdAt
                    .orEmpty(),

            updatedAt =
                initialPolicy
                    ?.updatedAt
                    .orEmpty(),

            expiresAt =
                initialPolicy
                    ?.expiresAt,

            reasonTag =
                initialPolicy
                    ?.reasonTag
        )
    }
}
